# Site settings
title: Education Frontiers
email: contact@education-frontiers.com 
url: https://education-frontiers.com
baseurl: /
description: "This is the website of Education Frontiers, a professional German as foreign language institute, located in Bayreuth, Germany."
keywords: "Education Frotniers, Learn German, Bayreuth, Rhethoriktraining, Universität, Coaching"
skills: "Education Frontiers, located in Bayreuth, offers language teaching as well as professional development and training programs for teachers and educators."
meta_author: Lutz Erik
favicon: ./img/logo-blue.ico


# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: erik

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 579aeb # 18bc9c #80B3FF
  primary-rgb: "87,154,235" #"128,179,255"
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F

# Footer settings
footer:
  copyright: Erik Lutz
  location: Location
  social: Follow us on
  infos: Infos

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: linkedin
    url: https://de.linkedin.com/in/erik-vinzenz-lutz-baa3421b3
  - title: instagram
    url: https://instagram.com
  - title: whatsapp
    url: tel:+49 163 4075936

# Postal address (add as many lines as necessary)
address:
  - line: Wilhelmsplatz 9
  - line: 95444 Bayreuth
  - line: +49 163 4075936

# Credits content
infos: Here you can find the <a href="/impressum/">impressum</a> and our <a href="/privacy-policy/">privacy policy</a>.

# Build settings
markdown: kramdown
permalink: pretty

#for posts
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      permalink: /:categories/:title/
